version: '3'
services:
  node-app:
    container_name: express-node-app-con
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
    env_file:
      - ./.env
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: example
  #mongo-express:
   # image: mongo-express
    #restart: always
    #depends_on:
     # - mongo
    #ports:
     # - 8081:8081
   # environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: example
     # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  redis:
    image: redis
  web:
    image: nginx:stable-alpine
    volumes:
      - /Users/mohamedbayoumy/Desktop/Docker_Work/node-app-postgres-redis-nginx/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - node-app
  
volumes:
  mongo_db:
  postgres_db:
